apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns-cronjob
  namespace: cloudflare-ddns
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      template:
        spec:
          containers:
          - name: cf-ddns
            image: ${IMAGE}
            envFrom:
              - secretRef:
                  name: secret-env-values
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure

