apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns-cronjob
  namespace: cloudflare-ddns
spec:
  schedule: "2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cf-ddns
            image: ${IMAGE}
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure

